version: "3.9"

services:
  postgres-docker:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=apisolid
